# Generated by Django 5.2.4 on 2025-07-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'HLBLNLINIOIMC', 'verbose_name_plural': 'лоотлдотлод'},
        ),
    ]
