# Generated by Django 5.2.4 on 2025-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='field',
            field=models.CharField(db_comment='', default=' ', verbose_name='ffvfevf'),
            preserve_default=False,
        ),
    ]
